export const FETCH_COUNTRY_LIST = "FETCH_COUNTRY_LIST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";
export const SEARCH_COUNTRY = "SEARCH_COUNTRY";
export const FILTER_COUNTRY = " FILTER_COUNTRY";
export const CHANGE_KEYWORD = "CHANGE_KEYWORD";
